---
  title: "Assignmnt"
author: "gp549@scarletmail.rutgers.edu"
date: "9/24/2023"
output: html_document
--

View(Typical_Employee_Survey_Data)

#Add Header Row 

colnames(Typical_Employee_Survey_Data) <- c("Age", "Gender","Satisfaction_of_the_Job","Job_Characteristics","Years_of_Experience","Promotion_Prediction","Allowance_of_Decision_Making","Budgetary_Decision_Participation","Proud_of_working_in_the_organization","Turn_down_another_job_for_more_pay","Relations_between_coworkers_and_colleagues")


#Print out the 5-point summary and boxplot (numerical columns) for each column (20 points)

fivenum(Typical_Employee_Survey_Data$Age)
fivenum(Typical_Employee_Survey_Data$Gender)
fivenum(Typical_Employee_Survey_Data$Satisfaction_of_the_Job)
fivenum(Typical_Employee_Survey_Data$Job_Characteristics)
fivenum(Typical_Employee_Survey_Data$Years_of_Experience)
fivenum(Typical_Employee_Survey_Data$Promotion_Prediction)
fivenum(Typical_Employee_Survey_Data$Allowance_of_Decision_Making)
fivenum(Typical_Employee_Survey_Data$Budgetary_Decision_Participation)
fivenum(Typical_Employee_Survey_Data$Proud_of_working_in_the_organization)
fivenum(Typical_Employee_Survey_Data$Turn_down_another_job_for_more_pay)
fivenum(Typical_Employee_Survey_Data$Relations_between_coworkers_and_colleagues)

boxplot(Typical_Employee_Survey_Data$Age)
boxplot(Typical_Employee_Survey_Data$Gender)
boxplot(Typical_Employee_Survey_Data$Satisfaction_of_the_Job)
boxplot(Typical_Employee_Survey_Data$Job_Characteristics)
boxplot(Typical_Employee_Survey_Data$Years_of_Experience)
boxplot(Typical_Employee_Survey_Data$Promotion_Prediction)
boxplot(Typical_Employee_Survey_Data$Allowance_of_Decision_Making)
boxplot(Typical_Employee_Survey_Data$Budgetary_Decision_Participation)
boxplot(Typical_Employee_Survey_Data$Proud_of_working_in_the_organization)
boxplot(Typical_Employee_Survey_Data$Turn_down_another_job_for_more_pay)
boxplot(Typical_Employee_Survey_Data$Relations_between_coworkers_and_colleagues)

#Convert the columns that need to be converted to Factors (10 points)

Typical_Employee_Survey_Data$Gender <- as.factor(Typical_Employee_Survey_Data$Gender)
Typical_Employee_Survey_Data$Gender <- as.numeric(Typical_Employee_Survey_Data$Gender)
Typical_Employee_Survey_Data$Years_of_Experience <- as.factor(Typical_Employee_Survey_Data$Years_of_Experience)
Typical_Employee_Survey_Data$Years_of_Experience <- as.numeric(Typical_Employee_Survey_Data$Years_of_Experience)

#Plot the right visual for each column (20 points)

hist(Typical_Employee_Survey_Data$Age)
hist(Typical_Employee_Survey_Data$Gender)
hist(Typical_Employee_Survey_Data$Satisfaction_of_the_Job)
hist(Typical_Employee_Survey_Data$Job_Characteristics)
hist(Typical_Employee_Survey_Data$Years_of_Experience)
hist(Typical_Employee_Survey_Data$Promotion_Prediction)
hist(Typical_Employee_Survey_Data$Allowance_of_Decision_Making)
hist(Typical_Employee_Survey_Data$Budgetary_Decision_Participation)
hist(Typical_Employee_Survey_Data$Proud_of_working_in_the_organization)
hist(Typical_Employee_Survey_Data$Turn_down_another_job_for_more_pay)
hist(Typical_Employee_Survey_Data$Relations_between_coworkers_and_colleagues)

#Plot scatter plots to show few relationships (20 points)

plot(Typical_Employee_Survey_Data$Age, Typical_Employee_Survey_Data$Gender, main="Scatter Plot", xlab="Age", ylab="Gender")
plot(Typical_Employee_Survey_Data$Satisfaction_of_the_Job, Typical_Employee_Survey_Data$Years_of_Experience, main="Scatter Plot", xlab="How much satisfied with the job", ylab="How many years of experience at the current employer")
plot(Typical_Employee_Survey_Data$Years_of_Experience, Typical_Employee_Survey_Data$Promotion_Prediction, main="Scatter Plot", xlab="How many years of experience at the current employer", ylab="Prediction of Promotion")
plot(Typical_Employee_Survey_Data$Allowance_of_Decision_Making, Typical_Employee_Survey_Data$Job_Characteristics, main="Scatter Plot", xlab="Allowance of making decisions ", ylab="Job Characteristics")
plot(Typical_Employee_Survey_Data$Years_of_Experience, Typical_Employee_Survey_Data$Turn_down_another_job_for_more_pay, main="Scatter Plot", xlab="How many years of experience at the current employer", ylab="Turn down another job for more pay")


